### ISSUE TITLE
Callbacks vs promise

### ISSUE THREAD

**Issue by HammadKhan70** [CreativeNob/Tricky-Javascript#2]

**Comment by CreativeNob** [comment]
You can explain

**Comment by HammadKhan70** [comment]
As compared to Callback function, It is very easy to debug the error with Promise like try-catch block. A promise made the chaining of functions straightforward and simplified the code. Common need of chaining is to execute two or more asynchronous operations back to back, making it much easier to read.12-Feb-2022
